package com.kirilo.swing;

import javax.swing.*;
import java.awt.*;

//http://skipy.ru/philosophy/visualDesigners.html
//https://intellij-support.jetbrains.com/hc/en-us/community/posts/207274005-No-Form-Main-option-in-generate-main-for-class-bound-to-swing-form
public class DirectoryDialog {
    public static void main(String[] args) {
        JFrame frame = new JFrame("DirectoryDialog");
        frame.setContentPane(new DirectoryDialog().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 300);
        frame.setLocationRelativeTo(null);
        frame.pack();
        frame.setVisible(true);
    }

    private JPanel mainPanel;
    private JComboBox chooseDriveComboBox;
    private JButton okButton;
    private JButton cancelButton;
    private JTree chooseDirectoryTree;
    private JButton createNewButton;
    private JButton projectRootButtonButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setMinimumSize(new Dimension(214, 142));
        mainPanel.setPreferredSize(new Dimension(400, 300));
        mainPanel.setRequestFocusEnabled(true);
        mainPanel.setVerifyInputWhenFocusTarget(true);
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null));
        final JLabel label1 = new JLabel();
        label1.setMaximumSize(new Dimension(70, 16));
        label1.setMinimumSize(new Dimension(70, 16));
        label1.setPreferredSize(new Dimension(70, 16));
        label1.setText("Choose Drive");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.SOUTHWEST;
        mainPanel.add(label1, gbc);
        chooseDriveComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("C:\\");
        defaultComboBoxModel1.addElement("D:\\");
        defaultComboBoxModel1.addElement("E:\\");
        chooseDriveComboBox.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(chooseDriveComboBox, gbc);
        okButton = new JButton();
        okButton.setActionCommand("Ok");
        okButton.setLabel("Ok");
        okButton.setText("Ok");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        mainPanel.add(okButton, gbc);
        final JLabel label2 = new JLabel();
        label2.setMaximumSize(new Dimension(91, 16));
        label2.setMinimumSize(new Dimension(91, 16));
        label2.setPreferredSize(new Dimension(91, 16));
        label2.setRequestFocusEnabled(true);
        label2.setText("Choose Directory");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.SOUTHWEST;
        mainPanel.add(label2, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        mainPanel.add(cancelButton, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(59, 360));
        scrollPane1.setRequestFocusEnabled(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane1, gbc);
        chooseDirectoryTree = new JTree();
        scrollPane1.setViewportView(chooseDirectoryTree);
        createNewButton = new JButton();
        createNewButton.setMaximumSize(new Dimension(100, 24));
        createNewButton.setMinimumSize(new Dimension(100, 24));
        createNewButton.setPreferredSize(new Dimension(100, 24));
        createNewButton.setText("createNewButton");
        createNewButton.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 10, 0);
        mainPanel.add(createNewButton, gbc);
        projectRootButtonButton = new JButton();
        projectRootButtonButton.setMaximumSize(new Dimension(104, 24));
        projectRootButtonButton.setMinimumSize(new Dimension(104, 24));
        projectRootButtonButton.setPreferredSize(new Dimension(104, 24));
        projectRootButtonButton.setText("projectRootButton");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        mainPanel.add(projectRootButtonButton, gbc);
        label1.setLabelFor(chooseDriveComboBox);
        label2.setLabelFor(scrollPane1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
